version: '3.8'

services:
  spark-master:
    build: .
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080" # Spark Master Web UI
      - "4040:4040" # Spark Job UI
    volumes:
      - .:/app
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    build: .
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - .:/app
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
